window.CHOOSE_A_LOSER_CONTENT = {
  version: '8',
  defaults: {
    proven: [
      {text:"Who is the tallest?",chaos:1},
      {text:"Who is the shortest?",chaos:1},
      {text:"If height were a podium, who gets silver?",chaos:1},
      {text:"Who has the longest hair?",chaos:1},
      {text:"Who has the shortest hair?",chaos:1},
      {text:"Who is wearing the most black?",chaos:1},
      {text:"Who is wearing the brightest colour?",chaos:1},
      {text:"Who is wearing the most different colours?",chaos:1},
      {text:"Who is wearing the most layers?",chaos:1},
      {text:"Who has the most visible pockets?",chaos:1},
      {text:"Who has the most jewellery on right now?",chaos:1},
      {text:"Who has the most visible tattoos?",chaos:1},
      {text:"Who has the biggest shoe size?",chaos:1},
      {text:"Who has the smallest shoe size?",chaos:1},
      {text:"Who has the biggest hands?",chaos:1},
      {text:"Who has the longest first name?",chaos:1},
      {text:"Who has the shortest first name?",chaos:1},
      {text:"Who has the most letters in their full name?",chaos:1},
      {text:"Who has the fewest letters in their full name?",chaos:1},
      {text:"Whose birthday comes next?",chaos:1},
      {text:"Whose birthday was most recent?",chaos:1},
      {text:"Who is the oldest?",chaos:1},
      {text:"Who is the youngest?",chaos:1},
      {text:"If age were race time, who takes the silver medal?",chaos:1},
      {text:"Who woke up earliest today?",chaos:1},
      {text:"Who woke up latest today?",chaos:1},
      {text:"Who had the least sleep last night?",chaos:1},
      {text:"Who had the most sleep last night?",chaos:1},
      {text:"Who has the lowest phone battery right now?",chaos:1},
      {text:"Who has the highest phone battery right now?",chaos:1},
      {text:"Whose phone battery is second from death?",chaos:1},
      {text:"Who has the most unread notifications right now?",chaos:1},
      {text:"Who has the most browser tabs open on their phone?",chaos:1},
      {text:"Who has the most photos on their phone?",chaos:1},
      {text:"Who has the highest screen time today?",chaos:1},
      {text:"Who has the lowest screen time today?",chaos:1},
      {text:"Who has the earliest alarm set for tomorrow?",chaos:1},
      {text:"Who has the latest alarm set for tomorrow?",chaos:1},
      {text:"Who got here first?",chaos:1},
      {text:"Who got here last?",chaos:1},
      {text:"Who travelled the furthest to be here?",chaos:1},
      {text:"Who lives closest to here?",chaos:1},
      {text:"Who has known the host the longest?",chaos:1},
      {text:"Who has known the host for the shortest time?",chaos:1},
      {text:"Who has lived at their current address the longest?",chaos:1},
      {text:"Who has lived at their current address the shortest time?",chaos:1},
      {text:"Who has been in their current job the longest?",chaos:1},
      {text:"Who started their current job most recently?",chaos:1},
      {text:"Who has the biggest family?",chaos:1},
      {text:"Who has the most siblings?",chaos:1},
      {text:"Who has the fewest siblings?",chaos:1},
      {text:"Who has the most pets?",chaos:1},
      {text:"Who got the highest grades at school?",chaos:1},
      {text:"Who left school most recently?",chaos:1},
      {text:"Who has been in a relationship for the longest?",chaos:1},
      {text:"Who has been single for the longest?",chaos:1},
      {text:"Who has been abroad to the most countries?",chaos:1},
      {text:"Who has travelled abroad most recently?",chaos:1},
      {text:"Who has the most keys on their keyring?",chaos:1},
      {text:"Who has the most things in their pockets right now?",chaos:1},
      {text:"Who has the most coins on them right now?",chaos:1},
      {text:"Who has the newest phone?",chaos:1},
      {text:"Who has had their current phone the longest?",chaos:1},
      {text:"Who ate most recently?",chaos:1},
      {text:"Who has had the most caffeine today?",chaos:1},
      {text:"Who has had the least caffeine today?",chaos:1},
      {text:"Who has the least money in their bank account right now?",chaos:3,insult:"Poor you :( ...but you're about to be poorer."},
      {text:"Who has the most money in their bank account right now?",chaos:3},
      {text:"Who has the largest credit-card balance?",chaos:3},
      {text:"Who has the highest monthly rent or mortgage?",chaos:3},
      {text:"Who earns the most?",chaos:3},
      {text:"Who earns the least?",chaos:3},
      {text:"Who has had the most sex this month?",chaos:3},
      {text:"Who has had the least sex this month?",chaos:3},
      {text:"Who has gone the longest without having sex?",chaos:3},
      {text:"Who has had the most serious relationships?",chaos:3},
      {text:"Who has had the longest relationship?",chaos:3},
      {text:"Who has been dumped the most times?",chaos:3},
      {text:"Who has dumped the most people?",chaos:3},
      {text:"Who has the highest body count?",chaos:3},
      {text:"Who has the most dating apps installed right now?",chaos:3},
      {text:"Who has the most unread messages from someone they're avoiding?",chaos:3},
      {text:"Who has blocked the most people?",chaos:3},
      {text:"Who has the most embarrassing recent search history?",chaos:3},
      {text:"Who spent the most money last weekend?",chaos:3},
      {text:"Who has spent the most on a single night out?",chaos:3},
      {text:"Who has the most subscriptions they forgot they pay for?",chaos:3},
      {text:"Who has the biggest overdraft limit?",chaos:3},
      {text:"Who has the lowest credit score?",chaos:3},
      {text:"Who owes the most money to another person?",chaos:3},
      {text:"Who is owed the most money by another person?",chaos:3},
      {text:"Who has had the most jobs?",chaos:3},
      {text:"Who has been fired the most times?",chaos:3},
      {text:"Who has called in sick the most this year?",chaos:3},
      {text:"Who has the most unused annual leave left?",chaos:3},
      {text:"Who has the most screenshots in their camera roll?",chaos:3},
      {text:"Who has the most unread emails?",chaos:3},
      {text:"Who has the oldest unread message?",chaos:3},
      {text:"Who has the most alarms set on their phone?",chaos:3},
      {text:"Who has spent the most time on their phone today?",chaos:3},
      {text:"Who has the least storage left on their phone?",chaos:3},
      {text:"Who has the most saved passwords?",chaos:3},
      {text:"Who has the most people in their blocked contacts?",chaos:3}
    ],
    debate: [
      {text:"Who is the most stubborn?",chaos:1},
      {text:"Who complains the most?",chaos:1},
      {text:"Who is most likely to be late?",chaos:1},
      {text:"Who would survive longest on a desert island?",chaos:1},
      {text:"Who would be the worst person to share a hotel room with?",chaos:1},
      {text:"Who would win an argument even when completely wrong?",chaos:1},
      {text:"Who would cope worst with losing their phone for 24 hours?",chaos:1},
      {text:"Who would do best on I'm a Celebrity?",chaos:1},
      {text:"Who would do best on The Traitors?",chaos:1},
      {text:"Who would do best on Taskmaster?",chaos:1},
      {text:"Who would do best on The Great British Bake Off?",chaos:1},
      {text:"Who would win a pub quiz with no help?",chaos:1},
      {text:"Who would make the best detective?",chaos:1},
      {text:"Who would make the worst detective?",chaos:1},
      {text:"Who would be the best pub landlord?",chaos:1},
      {text:"Who would be the best wedding planner?",chaos:1},
      {text:"Who would be the worst person to organise a group holiday?",chaos:1},
      {text:"Who would be the best tour guide?",chaos:1},
      {text:"Who would be best at running a restaurant?",chaos:1},
      {text:"Who would be best at running a B&B?",chaos:1},
      {text:"Who would be worst at keeping a surprise party secret?",chaos:1},
      {text:"Who would be best at negotiating a pay rise?",chaos:1},
      {text:"Who would be the best person to have beside you in an emergency?",chaos:1},
      {text:"Who would be the worst person to sit next to on a 12-hour flight?",chaos:1},
      {text:"Who would survive longest without internet?",chaos:1},
      {text:"Who would be best at living completely off-grid?",chaos:1},
      {text:"Who would cope best if they suddenly had to live on a boat?",chaos:1},
      {text:"Who would adapt fastest if they had to move abroad tomorrow?",chaos:1},
      {text:"Who would be best at hosting a dinner party for strangers?",chaos:1},
      {text:"Who would be most convincing as a teacher?",chaos:1},
      {text:"Who would be most convincing as a politician?",chaos:1},
      {text:"Who would be most likely to accidentally become famous?",chaos:1},
      {text:"Who would cope best with suddenly becoming a parent to triplets?",chaos:1},
      {text:"Who would be best at keeping calm during a flight emergency?",chaos:1},
      {text:"Who would survive longest in a haunted house alone?",chaos:1},
      {text:"Who would be the easiest person to live with?",chaos:1},
      {text:"Who would be the hardest person to live with?",chaos:1},
      {text:"Who has the coolest parents?",chaos:3},
      {text:"Who has the best relationship with their parents?",chaos:3},
      {text:"Who had the most traumatic childhood?",chaos:3},
      {text:"Who would leave their partner at the altar?",chaos:3},
      {text:"Who would get engaged on holiday after knowing someone for two weeks?",chaos:3},
      {text:"Who would cope best in prison?",chaos:3},
      {text:"Who would cope worst in prison?",chaos:3},
      {text:"Who would die first in a zombie apocalypse?",chaos:3},
      {text:"Who would die in a zombie apocalypse because they went back for their charger?",chaos:3},
      {text:"Who is most likely to accidentally join a cult?",chaos:3},
      {text:"Who would accidentally become the leader of a cult?",chaos:3},
      {text:"Who would become unbearable after a tiny amount of fame?",chaos:3},
      {text:"Who would be the first person exposed if everyone's private group chats leaked?",chaos:3},
      {text:"Who would be most convincing while being interrogated for something they definitely did?",chaos:3},
      {text:"Who could actually talk their way out of being arrested?",chaos:3},
      {text:"Who would be the biggest liability on a jury?",chaos:3},
      {text:"Who would sell out the group first for £100,000?",chaos:3},
      {text:"Who would accept £1 million to never speak to anyone here again?",chaos:3},
      {text:"Who would be most likely to marry for money and actually stay married?",chaos:3},
      {text:"Who would be most likely to marry someone none of the group likes?",chaos:3},
      {text:"Who would be first to sleep with someone on a reality TV show?",chaos:3},
      {text:"Who would be easiest to catfish?",chaos:3},
      {text:"Who would be hardest to catfish?",chaos:3},
      {text:"Who would be most likely to accidentally insult a celebrity to their face?",chaos:3},
      {text:"Who would be most likely to appear in a documentary for completely the wrong reason?",chaos:3},
      {text:"Who would be most likely to get barred from a casino?",chaos:3},
      {text:"Who would be most likely to buy a house after one viewing?",chaos:3},
      {text:"Who would be most likely to move country on a whim?",chaos:3},
      {text:"Who would fake their own death but forget to turn off location sharing?",chaos:3},
      {text:"Who would become a supervillain over a parking-space dispute?",chaos:3},
      {text:"Who would escape a cult and then leave it a one-star Google review?",chaos:3},
      {text:"Who would turn a minor neighbour dispute into a six-part documentary?",chaos:3},
      {text:"Who would volunteer to drive the getaway car and then ask where everyone is going?",chaos:3},
      {text:"Who would get banned from a country for something that started with 'it'll be fine'?",chaos:3},
      {text:"Who would be hardest to successfully blackmail?",chaos:3},
      {text:"Who would abandon the group first if you were all stranded abroad?",chaos:3},
      {text:"Who would last longest pretending to be someone else at a billionaire's wedding?",chaos:3},
      {text:"Who would fake a medical emergency to escape a terrible date?",chaos:3},
      {text:"Who would accidentally marry into a criminal family?",chaos:3},
      {text:"Who would buy a pub after two drinks because 'how hard can it be'?",chaos:3},
      {text:"Who would wake up owning a horse after a night out?",chaos:3},
      {text:"Who would get legally married as part of a joke that went too far?",chaos:3},
      {text:"Who would accidentally become someone's alibi?",chaos:3},
      {text:"Who would lie most convincingly on national television?",chaos:3},
      {text:"Who would get away with living under a fake identity for a year?",chaos:3},
      {text:"Who would accidentally befriend an international fugitive?",chaos:3},
      {text:"Who would find a suitcase of cash and genuinely keep it?",chaos:3},
      {text:"Who would get divorced over something incredibly petty?",chaos:3},
      {text:"Who would hire a private investigator over something one text could solve?",chaos:3},
      {text:"Who would have their wedding objected to and not even be surprised?",chaos:3},
      {text:"Who would end up on a yacht without knowing whose yacht it is?",chaos:3},
      {text:"Who would accidentally become involved in a political scandal?",chaos:3},
      {text:"Who would be the worst person to suddenly become extremely rich?",chaos:3},
      {text:"Who would be the first to crack under interrogation?",chaos:3},
      {text:"Who would be most likely to have a secret second life?",chaos:3},
      {text:"Who would be most likely to disappear for six months and come back married?",chaos:3},
      {text:"Who would be most likely to ruin Christmas over a board game?",chaos:3}
    ],
    knockout: [
      {text:"What is 12 × 8?",answer:"96",explain:"12 × 8 = 96.",chaos:1},
      {text:"Which planet is known as the Red Planet?",answer:"Mars",explain:"Iron minerals make Mars look reddish.",chaos:1},
      {text:"What is the capital of Australia?",answer:"Canberra",explain:"Not Sydney or Melbourne.",chaos:1},
      {text:"What gas do plants absorb from the atmosphere?",answer:"Carbon dioxide",explain:"Plants use it during photosynthesis.",chaos:1},
      {text:"What is 15% of 200?",answer:"30",explain:"10% is 20 and 5% is 10.",chaos:1},
      {text:"What has keys but cannot open locks?",answer:"A piano",explain:"Correct. It was a piano.",chaos:1},
      {text:"How many sides does a hexagon have?",answer:"6",explain:"Hexa means six.",chaos:1},
      {text:"Which ocean is the largest?",answer:"Pacific Ocean",explain:"The Pacific is the largest ocean.",chaos:1},
      {text:"What is the chemical symbol for gold?",answer:"Au",explain:"Au comes from aurum.",chaos:1},
      {text:"What is 144 divided by 12?",answer:"12",explain:"144 ÷ 12 = 12.",chaos:1},
      {text:"Which country is home to the city of Dubrovnik?",answer:"Croatia",explain:"Dubrovnik is on Croatia's Adriatic coast.",chaos:1},
      {text:"How many minutes are in 2.5 hours?",answer:"150",explain:"2 hours = 120 minutes, plus 30.",chaos:1},
      {text:"Which organ pumps blood around the body?",answer:"The heart",explain:"The heart pumps blood through the circulatory system.",chaos:1},
      {text:"What is the square root of 81?",answer:"9",explain:"9 × 9 = 81.",chaos:1},
      {text:"Which language is primarily spoken in Brazil?",answer:"Portuguese",explain:"Brazil's official language is Portuguese.",chaos:1},
      {text:"How many sides does a dodecagon have?",answer:"12",explain:"Dodeca means twelve.",chaos:3},
      {text:"Which element has the chemical symbol Fe?",answer:"Iron",explain:"Fe comes from ferrum.",chaos:3},
      {text:"If you overtake the person in second place, what place are you in?",answer:"Second place",explain:"You take their position.",chaos:3},
      {text:"What is the largest organ in the human body?",answer:"The skin",explain:"Skin is the largest organ.",chaos:3},
      {text:"A farmer has 17 sheep. All but 9 run away. How many remain?",answer:"9",explain:"All but 9 means 9 stayed.",chaos:3},
      {text:"What number comes next: 2, 3, 5, 8, 13, ?",answer:"21",explain:"Add the previous two.",chaos:3},
      {text:"What gets wetter the more it dries?",answer:"A towel",explain:"A towel gets wet while drying things.",chaos:3},
      {text:"Before Mount Everest was discovered, what was the highest mountain on Earth?",answer:"Mount Everest",explain:"It was still the highest mountain.",chaos:3},
      {text:"A rooster lays an egg on a roof. Which side does it roll down?",answer:"Neither",explain:"Roosters do not lay eggs.",chaos:3},
      {text:"You have one match and enter a dark room with a candle, lamp and fireplace. What do you light first?",answer:"The match",explain:"You need the match first.",chaos:3},
      {text:"If there are 3 apples and you take away 2, how many do you have?",answer:"2",explain:"You took two.",chaos:3},
      {text:"What is 7 squared plus 1?",answer:"50",explain:"7² is 49, plus 1 is 50.",chaos:3},
      {text:"Which is heavier: a kilogram of steel or a kilogram of feathers?",answer:"They weigh the same",explain:"Both are one kilogram.",chaos:3},
      {text:"What word is spelled incorrectly in every dictionary?",answer:"Incorrectly",explain:"The word itself is 'incorrectly'.",chaos:3},
      {text:"How many months have 28 days?",answer:"12",explain:"Every month has at least 28 days.",chaos:3},
      {text:"What can travel around the world while staying in one corner?",answer:"A stamp",explain:"A stamp stays on the corner of an envelope.",chaos:3},
      {text:"What has a neck but no head?",answer:"A bottle",explain:"A bottle has a neck.",chaos:3},
      {text:"What becomes shorter as it gets older?",answer:"A candle",explain:"A candle burns down over time.",chaos:3},
      {text:"What is the only even prime number?",answer:"2",explain:"All other even numbers are divisible by 2.",chaos:3},
      {text:"What is 1% of 1,000?",answer:"10",explain:"One hundredth of 1,000 is 10.",chaos:3}
    ],
    whoSaid: []
  },
  gates: [
    {q:"What colour do you get by mixing blue and yellow?",c:["Green","Purple","Orange"],a:0},
    {q:"What is the capital of France?",c:["Paris","Rome","Madrid"],a:0},
    {q:"Which language is mainly spoken in Brazil?",c:["Portuguese","Spanish","French"],a:0},
    {q:"What is 6 × 7?",c:["42","36","48"],a:0},
    {q:"How many rings are on the Olympic symbol?",c:["5","4","6"],a:0},
    {q:"Which planet is famous for its rings?",c:["Saturn","Mercury","Earth"],a:0},
    {q:"What is half of 90?",c:["45","40","50"],a:0},
    {q:"Which fruit is used to make guacamole?",c:["Avocado","Kiwi","Lime"],a:0},
    {q:"How many days are in a leap year?",c:["366","365","364"],a:0},
    {q:"Which animal is the largest land mammal?",c:["Elephant","Giraffe","Rhino"],a:0}
  ],
  skipInsults: [
    "Nobody knew that? Concerning, but statistically one of you had to be the stupidest.",
    "Not one answer. Excellent group performance.",
    "You may skip it. The allegations remain.",
    "Collective brain cell currently unavailable.",
    "Even a confidently wrong answer would have shown initiative.",
    "I expected nothing and somehow need to recalibrate lower.",
    "Nobody knew? Delete the evidence and move on.",
    "Interesting strategy. Unfortunately the question did have a correct answer."
  ],
  insults: [
    "That was academically concerning.",
    "Your final answer was apparently 'vibes'.",
    "You did not lose. You were simply never in danger of winning.",
    "The lights were on. The brain had Do Not Disturb enabled.",
    "You made common knowledge feel paywalled.",
    "I have seen stronger cognitive performance from a loading icon.",
    "The confidence-to-accuracy ratio needs investigating.",
    "A fascinating contribution to the decline of standards.",
    "You had every opportunity to know that.",
    "I would ask what happened, but I think we all watched it happen.",
    "That answer had the structural integrity of wet cardboard.",
    "Strong conviction. Shame about the facts.",
    "You have been defeated by information available to the general public.",
    "Please do not make this your LinkedIn headline."
  ]
};
window.addEventListener('DOMContentLoaded',()=>{
  let storedSettings={};try{storedSettings=JSON.parse(localStorage.getItem('chooseLoserSettings')||'{}')}catch{}
  settings.debateTimer=Number(storedSettings.debateTimer||15);
  const knockoutRow=document.getElementById('timerSetting')?.closest('.settingRow');
  if(knockoutRow&&!document.getElementById('debateTimerSetting')){
    const debateRow=document.createElement('div');debateRow.className='settingRow';
    debateRow.innerHTML=`<label>Debatable timer: <span id="debateTimerSettingValue">${settings.debateTimer}</span>s</label><input id="debateTimerSetting" type="range" min="5" max="60" step="5" value="${settings.debateTimer}" oninput="updateDebateTimerSetting(this.value)">`;
    knockoutRow.parentNode.insertBefore(debateRow,knockoutRow);
  }
  const originalOpenSettings=window.openSettings;
  window.openSettings=function(){originalOpenSettings();const slider=document.getElementById('debateTimerSetting'),value=document.getElementById('debateTimerSettingValue');if(slider)slider.value=settings.debateTimer;if(value)value.textContent=settings.debateTimer;};
  window.updateDebateTimerSetting=function(v){settings.debateTimer=+v;const value=document.getElementById('debateTimerSettingValue');if(value)value.textContent=v;saveSettings();};
  window.startTimer=function(r,n,done){stopTimer();const total=r==='debateTimer'?settings.debateTimer:settings.timer;let s=total,ring=document.getElementById(r),num=document.getElementById(n);num.textContent=s;ring.style.setProperty('--p','100%');timer=setInterval(()=>{s--;num.textContent=s;ring.style.setProperty('--p',(s/total*100)+'%');if(s<=0){stopTimer();done();}},1000);};
  try{const custom=JSON.parse(localStorage.getItem('chooseLoserCustomInsults')||'[]');const cleaned=custom.filter(x=>!/polyester/i.test(String(x)));if(cleaned.length!==custom.length)localStorage.setItem('chooseLoserCustomInsults',JSON.stringify(cleaned));}catch{}
  const rouletteQuips={
    "Who has the least money in their bank account right now?":"Poor you :( ...but you're about to be poorer.",
    "Who has the most money in their bank account right now?":"Congratulations on winning capitalism. Unfortunately, you've also won the bill.",
    "Who has the largest credit-card balance?":"Your credit card has been doing cardio.",
    "Who has the highest monthly rent or mortgage?":"Congratulations, your landlord is tonight's real winner.",
    "Who earns the most?":"Excellent. We've found the sponsor.",
    "Who earns the least?":"A brave contribution from the budget department.",
    "Who has had the most sex this month?":"Congratulations. Hydrate.",
    "Who has had the least sex this month?":"A moment of silence for your calendar.",
    "Who has gone the longest without having sex?":"At this point it's basically a sabbatical.",
    "Who has had the most serious relationships?":"Experienced applicant. References available.",
    "Who has had the longest relationship?":"Commitment detected. We can exploit that.",
    "Who has been dumped the most times?":"Statistically, the market has spoken.",
    "Who has dumped the most people?":"HR would like a word.",
    "Who has the highest body count?":"Your LinkedIn says 'extensive experience'.",
    "Who has the most dating apps installed right now?":"A diversified portfolio.",
    "Who has the most unread messages from someone they're avoiding?":"Avoidance has entered the chat.",
    "Who has blocked the most people?":"Your boundary list has a guest list.",
    "Who has the most embarrassing recent search history?":"Incognito was invented for a reason.",
    "Who spent the most money last weekend?":"Thank you for personally stimulating the economy.",
    "Who has spent the most on a single night out?":"A fiscal crime scene.",
    "Who has the most subscriptions they forgot they pay for?":"You're funding companies you don't even remember meeting.",
    "Who has the biggest overdraft limit?":"The bank believes in you more than you do.",
    "Who has the lowest credit score?":"The algorithm has concerns.",
    "Who owes the most money to another person?":"Your creditor is suddenly very interested in this round.",
    "Who is owed the most money by another person?":"Congratulations, you're now accepting repayment in drinks.",
    "Who has had the most jobs?":"Your CV has seasons.",
    "Who has been fired the most times?":"A rich and varied exit-interview history.",
    "Who has called in sick the most this year?":"Attendance: conceptual.",
    "Who has the most unused annual leave left?":"Your employer thanks you for the donation.",
    "Who has the most screenshots in their camera roll?":"Your phone is less a camera roll and more an evidence locker.",
    "Who has the most unread emails?":"Inbox zero has blocked you.",
    "Who has the oldest unread message?":"Archaeologists have been notified.",
    "Who has the most alarms set on their phone?":"Trust issues, but with mornings.",
    "Who has spent the most time on their phone today?":"Your phone would like to list you as a dependent.",
    "Who has the least storage left on their phone?":"Delete 14,000 screenshots or accept your fate.",
    "Who has the most saved passwords?":"Cybersecurity roulette. Bold.",
    "Who has the most people in their blocked contacts?":"A small private prison, apparently."
  };
  const applyRouletteQuips=list=>{if(!Array.isArray(list))return;list.forEach(q=>{const quip=rouletteQuips[q.text];if(quip)q.insult=quip;});};
  applyRouletteQuips(DEFAULTS.proven);applyRouletteQuips(data.proven);
  if(!document.getElementById('loadingMotionStyles')){
    const style=document.createElement('style');style.id='loadingMotionStyles';style.textContent=`
      #loadingScreen{overflow:hidden}
      #loadingScreen #loadingAxo{position:relative;z-index:2;transform-origin:50% 58%}
      #loadingScreen.active #loadingAxo{animation:axoThinkTilt 3s steps(1,end) infinite}
      @keyframes axoThinkTilt{0%,100%{transform:rotate(-5deg)}22%{transform:rotate(0deg)}44%{transform:rotate(5deg)}66%{transform:rotate(0deg)}82%{transform:rotate(-3deg)}}
      .thoughtBubbles{position:absolute;left:50%;top:50%;width:300px;height:220px;transform:translate(-50%,-57%);pointer-events:none;z-index:3}
      .thoughtBubble{position:absolute;border:2px solid rgba(210,239,255,.82);border-radius:50%;background:rgba(171,225,255,.10);box-shadow:inset 2px 2px 5px rgba(255,255,255,.22);opacity:0;animation:bubbleUp 2.25s ease-out infinite}
      .thoughtBubble:nth-child(1){width:10px;height:10px;left:58%;top:53%;animation-delay:0s}.thoughtBubble:nth-child(2){width:15px;height:15px;left:63%;top:48%;animation-delay:.35s}.thoughtBubble:nth-child(3){width:8px;height:8px;left:55%;top:52%;animation-delay:.75s}.thoughtBubble:nth-child(4){width:19px;height:19px;left:67%;top:45%;animation-delay:1.1s}.thoughtBubble:nth-child(5){width:11px;height:11px;left:61%;top:50%;animation-delay:1.45s}.thoughtBubble:nth-child(6){width:14px;height:14px;left:57%;top:49%;animation-delay:1.8s}
      @keyframes bubbleUp{0%{transform:translate(0,8px) scale(.65);opacity:0}15%{opacity:.85}75%{opacity:.65}100%{transform:translate(38px,-105px) scale(1.18);opacity:0}}
    `;document.head.appendChild(style);
  }
  const loadingScreen=document.getElementById('loadingScreen');
  if(loadingScreen&&!loadingScreen.querySelector('.thoughtBubbles')){
    const bubbles=document.createElement('div');bubbles.className='thoughtBubbles';bubbles.innerHTML='<i class="thoughtBubble"></i><i class="thoughtBubble"></i><i class="thoughtBubble"></i><i class="thoughtBubble"></i><i class="thoughtBubble"></i><i class="thoughtBubble"></i>';loadingScreen.appendChild(bubbles);
  }
  window.randomLoading=function(cb){document.getElementById('loadingAxo').innerHTML=axo(chaos===3?'unhinged':'neutral');showScreen('loadingScreen');setTimeout(cb,3000);};
  const originalShowScreen=window.showScreen;const initialHoldUntil=Date.now()+3000;let initialHomeQueued=false;
  window.showScreen=function(id){if(id==='homeScreen'&&Date.now()<initialHoldUntil){if(!initialHomeQueued){initialHomeQueued=true;setTimeout(()=>originalShowScreen('homeScreen'),Math.max(0,initialHoldUntil-Date.now()));}return;}return originalShowScreen(id);};
});
window.addEventListener('DOMContentLoaded',()=>{
  const familyQuips={
    "Who is the tallest?":"Enjoy the view. You're still paying.",
    "Who is the shortest?":"Compact. Efficient. Financially liable.",
    "If height were a podium, who gets silver?":"Second place in height. First place in consequences.",
    "Who has the longest hair?":"Rapunzel, but the tower has a bar tab.",
    "Who has the shortest hair?":"Less hair, same liability.",
    "Who is wearing the most black?":"Dressed for the funeral of your bank balance.",
    "Who is wearing the brightest colour?":"Easy to identify. Convenient.",
    "Who is wearing the most different colours?":"A visual warning label.",
    "Who is wearing the most layers?":"Peel responsibly.",
    "Who has the most visible pockets?":"Excellent. Plenty of places to hide the receipt.",
    "Who has the most jewellery on right now?":"Portable assets detected.",
    "Who has the most visible tattoos?":"Permanent decisions. Temporary wealth.",
    "Who has the biggest shoe size?":"Big footprint. Bigger bill.",
    "Who has the smallest shoe size?":"Tiny shoes, adult-sized consequences.",
    "Who has the biggest hands?":"Perfect for holding the bill.",
    "Who has the longest first name?":"More letters, more liability.",
    "Who has the shortest first name?":"Efficient name. Inefficient luck.",
    "Who has the most letters in their full name?":"Your name needs pagination.",
    "Who has the fewest letters in their full name?":"Minimalist branding. Maximum exposure.",
    "Whose birthday comes next?":"Early birthday present: the bill.",
    "Whose birthday was most recent?":"Hope you kept the birthday money.",
    "Who is the oldest?":"Wisdom allegedly comes with age. Use some.",
    "Who is the youngest?":"Youth has consequences.",
    "If age were race time, who takes the silver medal?":"Silver medal. Gold-standard bad luck.",
    "Who woke up earliest today?":"All that extra day, and it led here.",
    "Who woke up latest today?":"Good morning. You owe us.",
    "Who had the least sleep last night?":"Sleep-deprived and now financially compromised.",
    "Who had the most sleep last night?":"Well-rested enough to process this loss.",
    "Who has the lowest phone battery right now?":"Your phone and finances are both in low-power mode.",
    "Who has the highest phone battery right now?":"Excellent. You can Apple Pay.",
    "Whose phone battery is second from death?":"Not dead yet. Your bank balance might be.",
    "Who has the most unread notifications right now?":"Even your phone is trying to tell you something.",
    "Who has the most browser tabs open on their phone?":"Close a tab. Open your banking app.",
    "Who has the most photos on their phone?":"A historian. Unfortunately history remembers this.",
    "Who has the highest screen time today?":"Your screen knows you better than we do.",
    "Who has the lowest screen time today?":"Touching grass didn't save you.",
    "Who has the earliest alarm set for tomorrow?":"Tomorrow starts early. Tonight ends expensive.",
    "Who has the latest alarm set for tomorrow?":"Sleep in. You've earned absolutely nothing.",
    "Who got here first?":"First here, first punished.",
    "Who got here last?":"Late and still somehow selected.",
    "Who travelled the furthest to be here?":"You came all this way for this.",
    "Who lives closest to here?":"At least the walk of shame is short.",
    "Who has known the host the longest?":"Loyalty has finally stopped paying.",
    "Who has known the host for the shortest time?":"Welcome. This is your initiation fee.",
    "Who has lived at their current address the longest?":"Stable housing, unstable outcome.",
    "Who has lived at their current address the shortest time?":"New home, old problem.",
    "Who has been in their current job the longest?":"Seniority has benefits. This is not one.",
    "Who started their current job most recently?":"Probation period just got expensive.",
    "Who has the biggest family?":"Excellent. Start a collection.",
    "Who has the most siblings?":"Surely one of them can lend you money.",
    "Who has the fewest siblings?":"No sibling bailout. Tragic.",
    "Who has the most pets?":"Tell the dependants dinner may be delayed.",
    "Who got the highest grades at school?":"All that academic promise, and here we are.",
    "Who left school most recently?":"Education may be over. Fees continue.",
    "Who has been in a relationship for the longest?":"Commitment champion. Commit to the bill.",
    "Who has been single for the longest?":"Independent in love. Not in payment.",
    "Who has been abroad to the most countries?":"Well-travelled, poorly protected.",
    "Who has travelled abroad most recently?":"Holiday glow, domestic consequences.",
    "Who has the most keys on their keyring?":"Keyholder. Unfortunately not to financial freedom.",
    "Who has the most things in their pockets right now?":"Inventory full. Wallet about to empty.",
    "Who has the most coins on them right now?":"Perfect. We accept exact change.",
    "Who has the newest phone?":"Shiny phone, dirty outcome.",
    "Who has had their current phone the longest?":"Loyal to a handset. Betrayed by an axolotl.",
    "Who ate most recently?":"Good. You won't be paying on an empty stomach.",
    "Who has had the most caffeine today?":"Heart racing? Wait till you see the bill.",
    "Who has had the least caffeine today?":"Sober nervous system. Same bad luck."
  };
  const applyFamilyQuips=list=>{if(!Array.isArray(list))return;list.forEach(q=>{const quip=familyQuips[q.text];if(quip)q.insult=quip;});};
  applyFamilyQuips(DEFAULTS.proven);applyFamilyQuips(data.proven);
  const motionStyle=document.getElementById('loadingMotionStyles');
  if(motionStyle)motionStyle.textContent=`
    #loadingScreen{overflow:hidden}
    #loadingScreen #loadingAxo{position:relative;z-index:2;transform-origin:50% 58%}
    #loadingScreen.active #loadingAxo{animation:axoThinkTilt .7s step-end infinite}
    @keyframes axoThinkTilt{0%,49.999%{transform:rotate(-7deg)}50%,100%{transform:rotate(7deg)}}
    .thoughtBubbles{position:absolute;left:50%;top:50%;width:300px;height:220px;transform:translate(-50%,-57%);pointer-events:none;z-index:3}
    .thoughtBubble{position:absolute;border:2px solid rgba(210,239,255,.82);border-radius:50%;background:rgba(171,225,255,.10);box-shadow:inset 2px 2px 5px rgba(255,255,255,.22);opacity:0;animation:bubbleUp 2.25s ease-out infinite}
    .thoughtBubble:nth-child(1){width:10px;height:10px;left:58%;top:53%;animation-delay:0s}.thoughtBubble:nth-child(2){width:15px;height:15px;left:63%;top:48%;animation-delay:.35s}.thoughtBubble:nth-child(3){width:8px;height:8px;left:55%;top:52%;animation-delay:.75s}.thoughtBubble:nth-child(4){width:19px;height:19px;left:67%;top:45%;animation-delay:1.1s}.thoughtBubble:nth-child(5){width:11px;height:11px;left:61%;top:50%;animation-delay:1.45s}.thoughtBubble:nth-child(6){width:14px;height:14px;left:57%;top:49%;animation-delay:1.8s}
    @keyframes bubbleUp{0%{transform:translate(0,8px) scale(.65);opacity:0}15%{opacity:.85}75%{opacity:.65}100%{transform:translate(38px,-105px) scale(1.18);opacity:0}}
  `;
  document.querySelectorAll('.modeButton.proof .bt').forEach(el=>{if(el.textContent.includes('Anything Goes'))el.textContent="🍬 Pick 'n' Mix";});
  document.querySelectorAll('.colourControl span').forEach(el=>{if(el.textContent.trim()==='Anything Goes')el.textContent="Pick 'n' Mix";});
  const previousOpenEditor=window.openEditor;
  window.openEditor=function(mode){previousOpenEditor(mode);if(mode==='proven')document.getElementById('editorTitle').textContent="Edit Pick 'n' Mix";};
});